### ISSUE TITLE
[Bug] Gaia fica invisível ao ser spawnado

### ISSUE THREAD

**Issue by SrAnthony** [TheKingdomServer/JordannPack#2]
Está acontecendo com a maioria dos jogadores.
Já foi testado e comprovado.
Está acontecendo no singleplayer também, então descartada a hipótese de ser problema com o servidor.

**Comment by Eufranio** [comment]
Botania não vai atualizar mais então, descartada a possibilidade de ser resolvido (pelo vazkii).

**Comment by SrAnthony** [comment]
Problema descoberto.
A culpa é do mod SkinPort. Se alguém estiver com o mod e estiver com uma skin da 1.8 o gaia vai aparecer. Já se estiver com o mod e uma skin da 1.7 (aquela sem a segunda camada) o gaia vai ficar invisível.
Já pedi suporte para o desenvolvedor do mod SkinPort e estou aguardando resposta.

**Comment by Esctogrillo** [comment]
#https://github.com/zlainsama/SkinPort/issues/9

**Comment by SrAnthony** [comment]
O problema foi parcialmente resolvido.
Colocamos uma mensagem nos itens necessários para spawnar o gaia, informando que se o gaia aparecer invisível é necessário remover o mod SkinPort.
