### ISSUE TITLE
Nao consigo entrar no server

### ISSUE THREAD

**Issue by ghost** [TheKingdomServer/JordannPack#4]
Quando entro na aba Multiplayer já esta la o IP mas o server não carrega, é como se estivesse offline.
P.S. Eu uso o MultiMc pirata mas ja consegui entrar noutros modpacks com servers

**Comment by ghost** [comment]
Por favor sejam rapidos a dar soluçoes pois eu quero mesmo jogar no vosso servidor
pf.

**Comment by ghost** [comment]
Não é a Ram http://prntscr.com/bpks1n

**Comment by ghost** [comment]
Ja troquei de java e tudo mas continua a nao dar

**Comment by ghost** [comment]
http://prntscr.com/bpkxlf

**Comment by ghost** [comment]
Podem responder pf?

**Comment by ghost** [comment]
N podem dar 1 resposta

**Comment by SrAnthony** [comment]
@condorgamer O servidor está fechado temporariamente, dê uma olhada no fórum: forum.thekingdomserver.com

**Comment by ghost** [comment]
Mas vai estar muito tempo fechado?

**Comment by SrAnthony** [comment]
@condorgamer Não tenho como prever uma data, mas vai ficar um bom tempo sim.
