### ISSUE TITLE
[Sugestão] Industrial Expansion

### ISSUE THREAD

**Issue by allanf181** [TheKingdomServer/JordannPack#5]
https://minecraft.curseforge.com/projects/industrial-expansion-te-addon

Melhor mod de todos. :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Eufranio** [comment]
kekekekekekeke
olá minetweaker

**Comment by SrAnthony** [comment]
Não é um mod muito requisitado e provavelmente nem será usado.
