### ISSUE TITLE
ERRO ao baixar pelo technic 

### ISSUE THREAD

**Issue by ledevmacedo** [TheKingdomServer/JordannPack#7]
Tentei baixar agora pelo Technic Launcher e apareceu o seguinte erro:

![erro](https://cloud.githubusercontent.com/assets/21015826/18412798/64973498-776e-11e6-9ab5-b3530d08bb5f.png)

**Comment by SrAnthony** [comment]
Foi um erro temporario na hospedagem e já foi resolvido.
